// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Decrement() {
  return window['go']['main']['App']['Decrement']();
}

export function GetInitialCount() {
  return window['go']['main']['App']['GetInitialCount']();
}

export function GetLimit() {
  return window['go']['main']['App']['GetLimit']();
}

export function Increment() {
  return window['go']['main']['App']['Increment']();
}

export function SetLimit() {
  return window['go']['main']['App']['SetLimit']();
}
