// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Decrement():Promise<number>;

export function GetInitialCount():Promise<number>;

export function GetLimit():Promise<number>;

export function Increment():Promise<number>;

export function Ping():Promise<boolean>;

export function SetLimit(arg1:number):Promise<number>;
